export interface ResourceSection {
  id: string;
  title: string;
  paragraphs: string[];
  checklist?: string[];
  links?: { label: string; href: string }[];
}
export interface Resource {
  slug: string;
  title: string;
  seoTitle: string;
  description: string;
  category: "Planning & budgets" | "Restaurants" | "Local search" | "Redesigns";
  published: string;
  modified: string;
  intro: string;
  sections: ResourceSection[];
  serviceSlug: string;
  related: string[];
}
const dates = { published: "2026-09-16", modified: "2026-09-16" };
export const resources: Resource[] = [
  {
    slug: "how-much-does-a-website-cost-in-austin", title: "How Much Does a Website Cost in Austin?", seoTitle: "What Does a Website Cost in Austin?",
    description: "Understand website pricing by scope, from a simple launch to custom development. Compare Forerunner’s published packages and the costs to include in a quote.",
    category: "Planning & budgets", ...dates, modified: "2026-09-17",
    intro: "The useful answer starts with what the website needs to do. A one-page introduction and a restaurant site with several menus, reservations, and private dining are different projects. Compare the work behind the number before comparing the number itself.",
    sections: [
      { id: "price-by-scope", title: "A concrete starting point: published project prices", paragraphs: ["Forerunner Sites currently lists three one-time project packages: Launch at $500 for a one-page website with up to five primary sections; Growth at $1,500 for up to five core pages; and Custom starting at $3,000 for a more involved scope. Hosting is billed separately at $50/month for Launch, $100/month for Growth, and $200/month for Custom. These are this studio’s prices, not a claimed average for Austin designers.", "Launch suits a focused introduction and inquiry path. Growth allows room for separate services, business information, and proof. Custom work starts with discovery because the page types, content structure, and integrations need to be defined before a final price makes sense. A booking link and a custom scheduling system are not equivalent deliverables."], links: [{label: "Compare Forerunner’s current packages and inclusions", href: "/pricing"}] },
      { id: "cost-drivers", title: "What changes the price", paragraphs: ["Count distinct layouts and customer journeys, not just pages. Five pages using one simple structure can take less work than a single page with complex interactive tools. Content is another major variable: organizing finished copy is different from researching, writing, and approving it.", "Photography, custom illustrations, product catalogs, accessibility remediation, data migrations, and provider integrations each need their own scope. If an estimate seems unusually low, ask which of these tasks you will be doing yourself. If it seems high, ask which deliverables account for the difference."], checklist: ["Page list and unique layouts", "Who writes copy and supplies approved photos", "Forms, booking, ordering, or payment integrations", "Editing needs and content management", "Existing URLs and migration requirements", "Feedback rounds, launch checks, and handoff"] },
      { id: "ongoing-costs", title: "Separate the build from the running costs", paragraphs: ["At Forerunner, twelve months of hosting plus the build totals $1,100 for Launch, $2,700 for Growth, and from $5,400 for Custom. This is a budgeting example, not an annual prepayment requirement. Growth includes two small changes each month; Custom includes two hours of updates and support. Domain renewal, business email, paid booking software, and work beyond the plan are separate. Ask for a first-year total and an ongoing annual estimate with third-party charges identified. If prices can change with usage, understand the trigger.", "Decide who receives renewal notices and owns the accounts. A lower initial price can be inconvenient if the business later needs to move its domain or export its content and cannot access either. At Forerunner, ownership of the domain, code, and accounts stays with the client; any support arrangement should still be written down."] },
      { id: "compare-quotes", title: "Make two quotes comparable", paragraphs: ["Give each designer the same short brief: the customer, the main action, the page list, the required tools, the launch deadline, and the content you already have. Request a written list of inclusions, exclusions, dependencies, and acceptance criteria.", "A proposal should explain what happens when the scope changes and when payments are due. Review the mobile experience in the designer’s actual work. Ask how a form is tested, how old links are preserved, and how you will know analytics is working. These questions reveal more than a collection of style references."], links: [{label: "See Austin website examples and the design process", href: "/austin-web-design"}] },
      { id: "next-step", title: "Choose the smallest scope that does the job well", paragraphs: ["Do not buy a large site because you might need every feature someday. Start with the services and actions that matter now, while leaving a sensible path to add content. Equally, do not force several unrelated services into one page if customers need detail to decide.", "Send your current website, the action you want visitors to take, and the pages you believe you need. That is enough to begin a useful scope conversation. A credible estimate can then explain what belongs in phase one and what can wait."], links: [{label: "Discuss your website scope", href: "/contact"}] },
    ], serviceSlug: "austin-web-design", related: ["how-much-should-small-business-spend-on-website", "website-redesign-checklist"],
  },
  {
    slug: "how-much-should-small-business-spend-on-website", title: "How Much Should a Small Business Spend on a Website?", seoTitle: "Small Business Website Budget Guide",
    description: "Choose a website budget based on your business stage, time, and needs. Compare DIY builders, freelancers, studios, agencies, and custom development fairly.",
    category: "Planning & budgets", ...dates, modified: "2026-09-17",
    intro: "Set the budget around a business problem you can name. If the goal is to explain a new offer and accept inquiries, the sensible investment is different from a system that manages orders, customer accounts, or several locations.",
    sections: [
      { id: "diy", title: "DIY: spend your time before spending on a team", paragraphs: ["A website builder can be a sensible choice when the offer is simple, the budget is tight, and someone has time to handle writing, layout, and updates. Templates provide a starting point. They do not decide what belongs on a page or test the customer journey for you.", "Before choosing a tool, try building the actual page you need. Check the mobile layout, form notifications, domain connection, and export options. Compare the plan that includes your required features, not just the advertised entry price. Include your own time in the decision even if it does not appear on an invoice."] },
      { id: "freelancer-studio", title: "Freelancers and small studios: direct access, defined capacity", paragraphs: ["A freelancer or owner-led studio can connect strategy, design, and implementation with fewer handoffs. This suits businesses that want help making decisions without coordinating a larger team. The tradeoff is capacity: clarify availability, support, and who handles work outside the person’s specialty.", "Forerunner’s published $500, $1,500, and $3,000+ packages give concrete examples of scopes, not a universal pricing rule. Monthly hosting adds $50, $100, or $200 respectively, with update allowances on Growth and Custom. Review the pricing page for limits. A budget is only useful when you know who provides content, which integrations are supported, and what happens after launch."], links: [{label: "Review small business website scopes", href: "/small-business-web-design-austin"}, {label: "Read the package comparison", href: "/pricing"}] },
      { id: "agency", title: "Agencies: pay for the team you actually need", paragraphs: ["A broader team may be appropriate when the project combines research, brand strategy, copywriting, photography, development, and stakeholder coordination. A larger organization can also need procurement, documentation, or service coverage a solo studio cannot reasonably provide.", "Ask who will do the work and how responsibilities are divided. A higher fee is not automatically waste, and a lower fee is not automatically value. Choose based on the capabilities the project needs and whether you will use them."] },
      { id: "custom-development", title: "Custom development: budget for behavior as well as pages", paragraphs: ["Custom development makes sense when the site must do something an existing tool cannot adequately support. Account systems, complex quoting, inventory, or operational workflows add requirements beyond a marketing website. They also add testing, security, maintenance, and support obligations.", "Start by checking whether a reputable existing service solves the problem. A supported booking integration may be easier to maintain than a bespoke scheduler. Ask for the ongoing maintenance implications alongside the initial build estimate."] },
      { id: "budget-test", title: "Use a break-even scenario, not a revenue promise", paragraphs: ["For illustration only, if a website costs $1,500 and an additional completed job contributes $300 after direct fulfillment costs, five genuinely incremental jobs would cover the build cost before ongoing expenses and tax. That arithmetic does not predict that the website will produce those jobs.", "Use your own contribution per job, not total sales revenue. Include hosting and support, consider how long you can wait, and ask how new customers will reach the site. If those inputs are unclear, keep the initial scope modest and measure before adding features."], checklist: ["What customer task will improve?", "Where will relevant visitors come from?", "What can the business afford without relying on hypothetical leads?", "Who maintains the site?", "Which features can wait for evidence?"] },
      { id: "brief", title: "Bring a practical brief to the first conversation", paragraphs: ["Write down your services, ideal customer, service area, primary action, content readiness, and comfortable budget range. Include the current website if there is one. A useful designer can then recommend a scope or explain why a simpler option is enough.", "The aim is a site you can launch, operate, and learn from. Spending more before the offer is clear rarely solves that uncertainty."], links: [{label: "Talk through the right scope for your business", href: "/contact"}] },
    ], serviceSlug: "small-business-web-design-austin", related: ["how-much-does-a-website-cost-in-austin", "website-redesign-checklist"],
  },
  {
    slug: "signs-restaurant-website-costing-customers", title: "7 Signs Your Restaurant Website Is Costing You Customers", seoTitle: "7 Restaurant Website Warning Signs",
    description: "Check seven common restaurant website problems, from unreadable menus to confusing reservations. Use simple guest tasks to identify what needs attention.",
    category: "Restaurants", ...dates,
    intro: "You cannot tell how many guests a website loses just by looking at it. You can spot obstacles that make choosing the restaurant harder. Run these seven checks on your own phone, then use booking data and guest feedback to decide what to fix first.",
    sections: [
      { id: "mobile", title: "1. The phone experience needs explanation", paragraphs: ["Open the site as a first-time guest. Can you read the text without zooming, close the menu easily, and tap the right action? A layout that technically fits the screen may still be difficult to use. Watch someone else try to find a table rather than coaching them through it.", "Fix overlapping controls, tiny targets, and important information hidden behind decorative sections. Test with the on-screen keyboard open if any inquiry form is part of the visit."] },
      { id: "menus", title: "2. Menus are buried or difficult to read", paragraphs: ["A guest should not have to guess whether a menu is current or download a large file to learn what dinner costs. Make the primary menu easy to find, keep text legible, and label brunch, happy hour, and other menus clearly.", "If you offer a PDF, keep it current and provide a useful mobile reading path too. Confirm dietary information with the restaurant rather than allowing old labels to persist through a redesign."] },
      { id: "speed", title: "3. The page waits for the atmosphere to load", paragraphs: ["A large video or several full-resolution photos can delay useful content, especially on mobile. Test on a normal connection, not only the restaurant’s Wi-Fi. Hours and the reservation link should be usable without waiting for every image.", "Resize photographs for their displayed use, reserve image space to avoid jumps, and load below-the-fold media when needed. Keep the restaurant’s character while reducing unnecessary payload."] },
      { id: "booking", title: "4. Reservations lead somewhere unexpected", paragraphs: ["Follow every reserve button through to the correct venue and booking provider. Check what happens when no tables are available and whether a widget works on a small screen. A link to a generic provider homepage is an extra task for the guest.", "Keep table reservations separate from private event inquiries. One needs availability; the other usually needs group size, occasion, date, and a conversation."] },
      { id: "information", title: "5. Hours, location, or offers contradict each other", paragraphs: ["Compare the website with the restaurant’s Business Profile and booking pages. Seasonal hours, holiday service, parking notes, and old promotions deserve an owner and an update routine. Conflicting details can make a guest call simply to verify that the restaurant is open.", "Put the location and directions near the visit-planning information. For multiple venues, make it unmistakable which location the menu and reservation apply to."] },
      { id: "search", title: "6. Search engines get less information than guests do", paragraphs: ["Important details embedded only in images are harder to maintain and less accessible than text. Give menus and location information descriptive headings, sensible links, and crawlable pages. Check that the public site is not accidentally marked noindex.", "Accurate business information and appropriate structured data help describe the restaurant. They do not replace a useful site or guarantee local rankings. Search Console can show whether key pages are indexed."], links: [{label: "Google’s guide to local search visibility", href: "https://support.google.com/business/answer/7091?hl=en"}] },
      { id: "cta", title: "7. Every button competes for attention", paragraphs: ["Reserve, order, view menus, buy a gift card, join rewards, and plan an event are all legitimate actions. They do not need equal weight in every section. Lead with the action that fits the page and make secondary paths available without overwhelming it.", "The Manuel’s case study shows how menus, Resy reservations, to-go ordering, and private dining can be organized into distinct journeys. It demonstrates the design approach; it does not claim a measured increase in bookings."], links: [{label: "Explore the Manuel’s restaurant website case study", href: "/work/manuels"}, {label: "Plan a restaurant website with clearer guest journeys", href: "/restaurant-web-design"}] },
    ], serviceSlug: "restaurant-web-design", related: ["restaurant-website-design-guide", "website-redesign-checklist"],
  },
  {
    slug: "local-seo-service-businesses-austin", title: "Local SEO for Austin Service Businesses: A Practical Guide", seoTitle: "Local SEO for Austin Service Businesses",
    description: "A practical local SEO guide covering Business Profiles, service pages, reviews, business details, internal links, and measurement for Austin service companies.",
    category: "Local search", ...dates,
    intro: "Local visibility starts with a clear description of what you do, where you actually work, and why a customer should trust you. For an Austin service business, the website and Business Profile should tell the same useful story. Neither is a shortcut to guaranteed rankings.",
    sections: [
      { id: "profile", title: "Start with an accurate, eligible Business Profile", paragraphs: ["Confirm eligibility before creating a Google Business Profile. Google generally requires in-person contact with customers; online-only businesses are not eligible. A service-area business should follow Google’s address and service-area rules rather than inventing a storefront.", "Use the real business name, appropriate category, current hours, working contact details, and a useful website link. Google describes local results in terms of relevance, distance, and prominence. You cannot buy a better organic local position, and a wider service-area setting is not a promise of wider ranking coverage."], links: [{label: "Google Business Profile eligibility requirements", href: "https://support.google.com/business/answer/13763036?hl=en"}, {label: "How Google describes local ranking", href: "https://support.google.com/business/answer/7091?hl=en"}] },
      { id: "service-pages", title: "Give each meaningful service a useful explanation", paragraphs: ["A window-cleaning customer and a roof-cleaning customer have different questions. Separate pages can make sense when the process, risks, pricing factors, or proof differ. Explain the actual service, exclusions, preparation, and request process rather than padding a page with keyword variants.", "State your genuine coverage. Austin, Lakeway, or West Austin references help when they explain where work happens. Do not generate a collection of identical city pages. A location page needs its own useful information, such as real local work, access considerations, or service availability."], links: [{label: "See a service-business website approach", href: "/service-business-web-design"}, {label: "Review the CleanZ ATX project", href: "/work/cleanz-atx"}] },
      { id: "reviews", title: "Build a review habit around completed work", paragraphs: ["Ask customers for honest feedback after a completed service. Do not write reviews for them, offer incentives, or filter the request so only happy customers get the link. Respond constructively and use permissioned quotes accurately if you feature them on the website.", "Real project photos, clear process details, and accurate credentials also help a customer evaluate you. Publish only qualifications and coverage the business can verify."], links: [{label: "Google Maps policy on fake engagement and reviews", href: "https://support.google.com/contributionpolicy/answer/7400114?hl=en"}] },
      { id: "business-details", title: "Keep business details and page relationships consistent", paragraphs: ["Use a consistent business name, public phone, and applicable address across your site and legitimate listings. Do not publish a private address just to complete an acronym or schema field. Link the service overview to detailed services, relevant projects, and the inquiry page.", "Use accurate Organization, LocalBusiness, or Service structured data where it fits the business. Markup should reflect visible facts. It cannot substitute for a missing service explanation, and self-published claims should not be dressed up as verified reviews."], links: [{label: "Google’s structured data guidelines", href: "https://developers.google.com/search/docs/appearance/structured-data/sd-policies"}] },
      { id: "technical", title: "Make the site easy to use and crawl", paragraphs: ["Keep important content in readable HTML, use descriptive page titles, publish canonical URLs, and include indexable pages in a sitemap. Check for broken links and accidental indexing blocks. Resize job photography and keep mobile forms practical.", "A useful local article can answer a question your customers actually ask, such as how to prepare for a service or what determines a quote. It should contain the business’s real knowledge, not just a city name in a generic article."], links: [{label: "Explore Austin website design and search foundations", href: "/austin-web-design"}] },
      { id: "measure", title: "Measure the quality of the inquiry", paragraphs: ["In Search Console, review indexing and the queries that bring relevant visitors. In analytics, separate contact-button clicks from accepted form submissions. In a simple lead log, record service requested, service area, source, quote, and whether the job was won.", "Review patterns over time rather than reacting to a single ranking check. If visits grow but inquiries are poor fits, improve the offer, coverage information, and qualification questions. If qualified visitors cannot finish the form, fix that path before publishing more content."], checklist: ["Profile and website details agree", "Key services have useful content", "Forms deliver and someone responds", "Search Console and analytics are connected", "Lead quality is reviewed monthly"] },
    ], serviceSlug: "service-business-web-design", related: ["how-much-should-small-business-spend-on-website", "website-redesign-checklist"],
  },
  {
    slug: "website-redesign-checklist", title: "Website Redesign Checklist for Small Businesses", seoTitle: "Small Business Website Redesign Checklist",
    description: "A practical redesign checklist for content, branding, mobile UX, SEO, redirects, forms, analytics, accessibility, and launch quality assurance.",
    category: "Redesigns", ...dates,
    intro: "A redesign changes more than the visual layer. Treat the existing site as an asset to inventory, not a folder to replace. Use this checklist to give every important page, customer action, and account an owner before launch.",
    sections: [
      { id: "baseline", title: "Before design: record what exists", paragraphs: ["Save a URL inventory and note which pages receive relevant search traffic or inquiries. Export available Search Console and analytics reports. Record the date range so later comparisons have context. If measurement is absent, say so rather than guessing at a baseline.", "Collect the domain, hosting, analytics, email, and integration account owners. Confirm who can approve content and how feedback will be consolidated. A blocked login can delay a launch as easily as an unfinished design."], checklist: ["Record all public URLs and important backlinks you know about", "List forms, booking tools, and integrations", "Save current page content and approved assets", "Document the primary customer action and success measure", "Confirm account access and launch responsibility"] },
      { id: "content-design", title: "Brand, navigation, and content", paragraphs: ["Decide which pages to keep, rewrite, merge, or retire. Give each a clear audience and purpose. The navigation should reflect customer tasks rather than internal departments. Use real photography and proof where available, with permission and accurate captions."], checklist: ["Confirm business name, services, hours, coverage, and contact details", "Approve typography, colors, and image direction", "Write headings that explain the page", "Make pricing expectations and next steps clear", "Agree on an editing workflow and content owner"] },
      { id: "mobile-accessibility", title: "Mobile UX, accessibility, and performance", paragraphs: ["Test complete tasks with a keyboard and on a phone. A form needs labels, helpful errors, a visible focus state, and a usable confirmation. Check text contrast, image alternatives, heading order, and reduced-motion behavior. Automated tools help identify issues but do not replace task testing.", "Look for large media, layout shifts, slow interactions, and unnecessary third-party scripts. Use field performance data when available; a single laboratory score is a diagnostic, not a guarantee of every visitor’s experience."], checklist: ["No horizontal overflow at phone and tablet widths", "Menu opens, closes, and supports keyboard use", "Forms remain usable with the mobile keyboard", "Images have dimensions and appropriate sizes", "Important actions work before optional media finishes loading"] },
      { id: "seo-migration", title: "SEO and migration", paragraphs: ["Preserve established URLs where practical. When a URL changes, redirect it to the most relevant replacement. Sending every old page to the homepage is rarely helpful. Retain useful content and check that staging restrictions do not follow the site into production."], checklist: ["Create an old-to-new URL redirect map", "Write unique titles and descriptions", "Set canonicals to the final public URLs", "Validate accurate structured data", "Update internal links and sitemap", "Check robots.txt and page-level indexing directives", "Verify HTTP, hostname, and trailing-slash behavior"], links: [{label: "Google’s site-move guidance", href: "https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes"}] },
      { id: "launch", title: "Launch QA: test the outcome, not just the button", paragraphs: ["Submit an approved test inquiry and confirm receipt in the destination inbox. Check reply-to behavior, validation, and the failure state. If booking happens in another tool, follow that handoff to the correct business and service.", "Keep a rollback path and a named person available for launch issues. Recheck the live domain after deployment; a working preview does not prove DNS, production credentials, or redirects are correct."], checklist: ["Verify all routes, assets, CTAs, and the 404 page", "Confirm analytics uses the correct property", "Separate click events from completed-lead events", "Check desktop, tablet, and mobile layouts", "Confirm production email delivery and scheduling", "Record the launch date and known limitations"] },
      { id: "after-launch", title: "After launch: review and improve", paragraphs: ["Submit the sitemap in Search Console and monitor indexing, broken URLs, and inquiries. Compare appropriate date ranges and account for seasonality, changes in traffic sources, and changes to the offer. Do not credit the design for every difference in revenue.", "The Manuel’s and CleanZ case studies show different content and conversion priorities. Your own redesign should start with the jobs your customers need to complete, then preserve the parts that already serve them."], links: [{label: "Plan an Austin website redesign", href: "/website-redesign-austin"}, {label: "See the Manuel’s website structure", href: "/work/manuels"}, {label: "See the CleanZ inquiry approach", href: "/work/cleanz-atx"}] },
    ], serviceSlug: "website-redesign-austin", related: ["how-much-does-a-website-cost-in-austin", "signs-restaurant-website-costing-customers"],
  },
  {
    slug: "restaurant-website-design-guide", title: "Restaurant Website Design: What Actually Drives Reservations", seoTitle: "Restaurant Website Design Guide",
    description: "Plan a restaurant website around the guest’s decision: mobile menus, photography, reservations, hours, directions, private dining, ordering, and local search.",
    category: "Restaurants", ...dates,
    intro: "A website cannot create table demand by design alone. It can help a guest understand the restaurant and remove obstacles between that decision and a reservation. Start with the visit the guest is trying to plan, then choose the content and interface that support it.",
    sections: [
      { id: "guest-tasks", title: "Design for three different guest tasks", paragraphs: ["A first-time diner asks whether the food, price, atmosphere, and location fit the occasion. A returning guest may only need to book or order. An event planner needs group details and a way to ask a more involved question. One long homepage cannot give all three tasks equal attention.", "Use clear navigation and a primary reservation action, then provide distinct menu, ordering, and private dining paths. Keep the information that makes the decision possible near the action itself."], links: [{label: "Explore restaurant website design services", href: "/restaurant-web-design"}] },
      { id: "menu-mobile", title: "Make the menu a readable part of the site", paragraphs: ["Organize menus around real service: dinner, brunch, drinks, happy hour, or another confirmed offering. Mobile text should be legible without zooming. Keep prices and dietary details current, and do not rely on a photo of a printed menu as the only way to read it.", "If the menu changes frequently, plan an update workflow the team can actually use. Confirm who edits it, who approves changes, and whether an optional PDF must also be replaced. A strong launch becomes less useful quickly if updates are impractical."] },
      { id: "reservation-path", title: "Give reservations a dependable handoff", paragraphs: ["A reservation button should lead to the correct venue and supported booking experience. Test on a phone, including the return path if the guest checks the menu again. An embed should not obscure navigation or make the page difficult to scroll.", "Where the booking provider supports completion tracking, distinguish a finished reservation from a click to the provider. If completion data is unavailable, report clicks honestly as outbound interest. Do not label every click a booked table."] },
      { id: "visit-details", title: "Answer the practical questions before they become a call", paragraphs: ["Publish current hours, address, directions, and relevant parking or access notes. Keep holiday changes aligned with your Business Profile and booking tools. Use location-specific information when there are multiple restaurants, so a guest does not reserve one venue while reading another’s menu.", "Photography should show the real food and room. Choose images that help someone judge the occasion, then optimize their size. Useful text and the reservation action should remain available while photography loads."] },
      { id: "other-revenue", title: "Give private dining, events, and ordering room to work", paragraphs: ["Private dining deserves information about the actual spaces, approved capacities, event types, and inquiry process. The form should ask enough to start a useful reply, such as date, group size, and occasion. Do not promise availability until the team confirms it.", "Takeout and online ordering should be labeled separately from dine-in reservations. Keep the provider link current and explain relevant pickup details. Events need dates and an update owner; expired announcements should not become the first impression of the restaurant."] },
      { id: "search-speed", title: "Support discovery without overwhelming the experience", paragraphs: ["Descriptive page titles, readable menus, consistent location details, and sensible internal links give search engines a clearer site to work with. Appropriate restaurant markup should describe verified facts. Review indexing in Search Console rather than assuming that a page is visible because it exists.", "Use responsive images, reserve their layout space, and avoid loading every video or widget immediately. Check real mobile tasks alongside performance diagnostics. The best tradeoff preserves the restaurant’s atmosphere while keeping the next action dependable."], links: [{label: "Google’s local ranking guidance", href: "https://support.google.com/business/answer/7091?hl=en"}] },
      { id: "example", title: "A concrete example: Manuel’s", paragraphs: ["Forerunner’s Manuel’s project organizes menus, Resy reservations, to-go ordering, private dining, gift cards, and rewards around distinct guest needs. Its visual direction takes cues from the restaurant itself rather than using a generic hospitality layout.", "The case study documents the structure and functionality. It does not publish an unverified reservation lift. For your own restaurant, agree on the measurement plan before launch, then review booking data alongside seasonality, promotions, and availability."], links: [{label: "Read the Manuel’s restaurant case study", href: "/work/manuels"}, {label: "Discuss your restaurant website", href: "/contact"}] },
    ], serviceSlug: "restaurant-web-design", related: ["signs-restaurant-website-costing-customers", "how-much-does-a-website-cost-in-austin"],
  },
];
export function getResource(slug: string) { return resources.find((resource) => resource.slug === slug); }
