import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import { NextResponse } from 'next/server.js';
const code = ts.transpileModule(fs.readFileSync('src/app/api/contact/route.ts','utf8'), {compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const env={RESEND_API_KEY:'mock-key'};
let sent;
let providerStatus=200;
const sandbox={exports:{},require:(name)=>name==='next/server'?{NextResponse}:{site:{name:'Forerunner Sites'}},process:{env},console:{error(){}},fetch:async(url,options)=>{sent={url,...JSON.parse(options.body)};return new Response('{}',{status:providerStatus});}};
vm.runInNewContext(code,sandbox);
const post = (body)=>sandbox.exports.POST(new Request('http://localhost/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));
for (const value of [null,[],42,'bad',{}, {name:'Name',email:'invalid',details:'Details'}]) assert.equal((await post(value)).status,400);
const malformed=await sandbox.exports.POST(new Request('http://localhost/api/contact',{method:'POST',body:'{'}));assert.equal(malformed.status,400);
const bot=await post({company_site:'spam'});assert.deepEqual(await bot.json(),{ok:true,delivered:false});assert.equal(sent,undefined);
const valid={name:'QA\r\nName',email:'qa@example.com',details:'<script>alert(1)</script>\nSecond line',package:'growth'};
let response=await post(valid);assert.equal(response.status,200);assert.deepEqual(await response.json(),{ok:true,delivered:true});
assert.deepEqual(sent.to,['lawbick@gmail.com']);assert.equal(sent.reply_to,'qa@example.com');assert.equal(sent.subject,'New project inquiry from QA Name');assert(!sent.html.includes('<script>'));assert(sent.html.includes('&lt;script&gt;'));
env.CONTACT_TO=' delivery@example.com ';await post(valid);assert.deepEqual(sent.to,['delivery@example.com']);
providerStatus=500;assert.equal((await post(valid)).status,502);
delete env.RESEND_API_KEY;assert.equal((await post(valid)).status,503);
console.log('PASS: contact shape validation, malformed JSON, honeypot, provider acceptance/failure, missing config, recipient isolation, reply-to and escaping. All provider calls mocked; no email sent.');
